// Generated by gen_meta.py
// DO NOT EDIT!

package meta

import (
	"kinger/gopuppy/network/protoc"
)

func init()  {

    protoc.RegisterMeta(&A2C_REGISTER_APP_Meta{})
    protoc.RegisterMeta(&GT2C_ON_CLIENT_ACCEPT_Meta{})
    protoc.RegisterMeta(&GT2C_ON_CLIENT_CLOSE_Meta{})
    protoc.RegisterMeta(&GT2C_CLIENT_RPC_CALL_Meta{})
    protoc.RegisterMeta(&GT2C_CLIENT_RPC_PUSH_Meta{})
    protoc.RegisterMeta(&C2GT_PUSH_CLIENT_Meta{})
    protoc.RegisterMeta(&L2C_REPORT_RPC_Meta{})
    protoc.RegisterMeta(&G2C_PLAYER_LOGIN_Meta{})
    protoc.RegisterMeta(&C2L_KICK_OUT_PLAYER_Meta{})
    protoc.RegisterMeta(&PLAYER_LOGIN_DONE_Meta{})
    protoc.RegisterMeta(&L2L_CALL_AGENT_Meta{})
    protoc.RegisterMeta(&L2L_PUSH_AGENT_Meta{})
    protoc.RegisterMeta(&L2CL_PUSH_CLIENT_Meta{})
    protoc.RegisterMeta(&L2C_SET_DISPATCH_Meta{})
    protoc.RegisterMeta(&L2L_NO_PLAYER_RPC_CALL_Meta{})
    protoc.RegisterMeta(&L2L_NO_PLAYER_RPC_PUSH_Meta{})
    protoc.RegisterMeta(&C2GT_BROADCAST_CLIENT_Meta{})
    protoc.RegisterMeta(&C2L_RESTORE_AGENT_Meta{})
    protoc.RegisterMeta(&LOAD_PLAYER_Meta{})
    protoc.RegisterMeta(&DEL_CLIENT_DISPATCH_INFO_Meta{})
    protoc.RegisterMeta(&C2GT_CLIENT_SET_FILTER_Meta{})
    protoc.RegisterMeta(&C2GT_CLIENT_CLEAR_FILTER_Meta{})
    protoc.RegisterMeta(&L2C_MQ_PUBLISH_Meta{})
    protoc.RegisterMeta(&L2C_MQ_ADD_CONSUMER_Meta{})
    protoc.RegisterMeta(&L2C_MQ_REMOVE_CONSUMER_Meta{})
    protoc.RegisterMeta(&C2L_MQ_CONSUME_Meta{})
    protoc.RegisterMeta(&GT2C_ON_SNET_DISCONNECT_Meta{})
    protoc.RegisterMeta(&GT2C_ON_SNET_RECONNECT_Meta{})
    protoc.RegisterMeta(&L2L_NO_PLAYER_BROADCAST_Meta{})
    protoc.RegisterMeta(&L2C_BEGIN_HOT_FIX_Meta{})
    protoc.RegisterMeta(&END_MONITOR_PLAYER_Meta{})
    protoc.RegisterMeta(&L2C_PLAYER_LOGOUT_Meta{})

}
